spring:
  datasource:
    url: ${MY_SQL_HONGIK_FESTA_TEST_URL}
    username: ${MY_SQL_HONGIK_FESTA_TEST_USERNAME}
    password: ${MY_SQL_HONGIK_FESTA_TEST_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true